### ISSUE TITLE
Pairing problem

### ISSUE THREAD

**Issue by sarthakaditya52** [Ferbez/OS-X-Atheros-3k-Firmware#1]
First of all thanks for updating this kext, I can finally use bluetooth.
The bluetooth is able to discover devices and connect to most of them and work fine.
But one of my bluetooth earphones are having trouble pairing with it...in bluetooth preferences it says that it's connected to the device but doesn't work. I've had this is issue with only one device I've tested so far.

If there's a way to resolve this issue please let me know

**Comment by Vvorcun** [comment]
More likely it's a firmware issue. All what this kext does is uploading linux firmware into device, and then macOS does the rest. You can achieve the same result with booting into linux/windows and rebooting into macOS (linux/windows uploads firmware which remains loaded after shutdown, so you need to reboot). I'm currently using this bluetooth with Sennheiser M2 OEBT and sometimes their audio device appears after a certain delay, so try to connect to you earphones and wait for like five minutes to see if it works.
